ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'PICKUP_PENDING';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'RETURN_PENDING';

ALTER TABLE "bookings"
ADD COLUMN IF NOT EXISTS "handoffInitiatedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "returnInitiatedAt" TIMESTAMP(3);
